# Changes here will be overwritten by Copier
_commit: 2.1.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: oliver.copping@diamond.ac.uk
author_name: Oliver Copping
component_owner: group:default/sscc
description: A Python softioc module for controlling the ARC detector HV Bias
distribution_name: arc-hvbias
docker: true
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: arc_hvbias
pypi: false
repo_name: arc-hvbias
type_checker: pyright
